import { countriesSchema } from "../types";


export const countries: countriesSchema = [
  {
    name: "Afghanistan",
    alpha2Code: "AF",
    emoji: "🇦🇫",
    flag: "https://restcountries.eu/data/afg.svg",
    callingCodes: ["+93"],
    currencyCode: "AFN",
  },
  {
    name: "Aland Islands",
    alpha2Code: "AX",
    emoji: "🇦🇽",
    flag: "https://restcountries.eu/data/ala.svg",
    callingCodes: ["+358"],
    currencyCode: "EUR",
  },
  {
    name: "Albania",
    alpha2Code: "AL",
    emoji: "🇦🇱",
    flag: "https://restcountries.eu/data/alb.svg",
    callingCodes: ["+355"],
    currencyCode: "ALL",
  },
  {
    name: "Algeria",
    alpha2Code: "DZ",
    emoji: "🇩🇿",
    flag: "https://restcountries.eu/data/dza.svg",
    callingCodes: ["+213"],
    currencyCode: "DZD",
  },
  {
    name: "American Samoa",
    alpha2Code: "AS",
    emoji: "🇦🇸",
    flag: "https://restcountries.eu/data/asm.svg",
    callingCodes: ["+1684"],
    currencyCode: "USD",
  },
  {
    name: "Andorra",
    alpha2Code: "AD",
    emoji: "🇦🇩",
    flag: "https://restcountries.eu/data/and.svg",
    callingCodes: ["+376"],
    currencyCode: "EUR",
  },
  {
    name: "Angola",
    alpha2Code: "AO",
    emoji: "🇦🇴",
    flag: "https://restcountries.eu/data/ago.svg",
    callingCodes: ["+244"],
    currencyCode: "AOA",
  },
  {
    name: "Anguilla",
    alpha2Code: "AI",
    emoji: "🇦🇮",
    flag: "https://restcountries.eu/data/aia.svg",
    callingCodes: ["+1264"],
    currencyCode: "XCD",
  },
  {
    name: "Antarctica",
    alpha2Code: "AQ",
    emoji: "🇦🇶",
    flag: "https://restcountries.eu/data/ata.svg",
    callingCodes: ["+672"],
    currencyCode: "",
  },
  {
    name: "Antigua and Barbuda",
    alpha2Code: "AG",
    emoji: "🇦🇬",
    flag: "https://restcountries.eu/data/atg.svg",
    callingCodes: ["+1268"],
    currencyCode: "XCD",
  },
  {
    name: "Argentina",
    alpha2Code: "AR",
    emoji: "🇦🇷",
    flag: "https://restcountries.eu/data/arg.svg",
    callingCodes: ["+54"],
    currencyCode: "ARS",
  },
  {
    name: "Armenia",
    alpha2Code: "AM",
    emoji: "🇦🇲",
    flag: "https://restcountries.eu/data/arm.svg",
    callingCodes: ["+374"],
    currencyCode: "AMD",
  },
  {
    name: "Aruba",
    alpha2Code: "AW",
    emoji: "🇦🇼",
    flag: "https://restcountries.eu/data/abw.svg",
    callingCodes: ["+297"],
    currencyCode: "AWG",
  },
  {
    name: "Australia",
    alpha2Code: "AU",
    emoji: "🇦🇺",
    flag: "https://restcountries.eu/data/aus.svg",
    callingCodes: ["+61"],
    currencyCode: "AUD",
  },
  {
    name: "Austria",
    alpha2Code: "AT",
    emoji: "🇦🇹",
    flag: "https://restcountries.eu/data/aut.svg",
    callingCodes: ["+43"],
    currencyCode: "EUR",
  },
  {
    name: "Azerbaijan",
    alpha2Code: "AZ",
    emoji: "🇦🇿",
    flag: "https://restcountries.eu/data/aze.svg",
    callingCodes: ["+994"],
    currencyCode: "AZN",
  },
  {
    name: "Bahamas",
    alpha2Code: "BS",
    emoji: "🇧🇸",
    flag: "https://restcountries.eu/data/bhs.svg",
    callingCodes: ["+1242"],
    currencyCode: "BSD",
  },
  {
    name: "Bahrain",
    alpha2Code: "BH",
    emoji: "🇧🇭",
    flag: "https://restcountries.eu/data/bhr.svg",
    callingCodes: ["+973"],
    currencyCode: "BHD",
  },
  {
    name: "Bangladesh",
    alpha2Code: "BD",
    emoji: "🇧🇩",
    flag: "https://restcountries.eu/data/bgd.svg",
    callingCodes: ["+880"],
    currencyCode: "BDT",
  },
  {
    name: "Barbados",
    alpha2Code: "BB",
    emoji: "🇧🇧",
    flag: "https://restcountries.eu/data/brb.svg",
    callingCodes: ["+1246"],
    currencyCode: "BBD",
  },
  {
    name: "Belarus",
    alpha2Code: "BY",
    emoji: "🇧🇾",
    flag: "https://restcountries.eu/data/blr.svg",
    callingCodes: ["+375"],
    currencyCode: "BYR",
  },
  {
    name: "Belgium",
    alpha2Code: "BE",
    emoji: "🇧🇪",
    flag: "https://restcountries.eu/data/bel.svg",
    callingCodes: ["+32"],
    currencyCode: "EUR",
  },
  {
    name: "Belize",
    alpha2Code: "BZ",
    emoji: "🇧🇿",
    flag: "https://restcountries.eu/data/blz.svg",
    callingCodes: ["+501"],
    currencyCode: "BZD",
  },
  {
    name: "Benin",
    alpha2Code: "BJ",
    emoji: "🇧🇯",
    flag: "https://restcountries.eu/data/ben.svg",
    callingCodes: ["+229"],
    currencyCode: "XOF",
  },
  {
    name: "Bermuda",
    alpha2Code: "BM",
    emoji: "🇧🇲",
    flag: "https://restcountries.eu/data/bmu.svg",
    callingCodes: ["+1441"],
    currencyCode: "BMD",
  },
  {
    name: "Bhutan",
    alpha2Code: "BT",
    emoji: "🇧🇹",
    flag: "https://restcountries.eu/data/btn.svg",
    callingCodes: ["+975"],
    currencyCode: "BTN",
  },
  {
    name: "Bolivia",
    alpha2Code: "BO",
    emoji: "🇧🇴",
    flag: "https://restcountries.eu/data/bol.svg",
    callingCodes: ["+591"],
    currencyCode: "BOB",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    alpha2Code: "BQ",
    emoji: "🇧🇶",
    flag: "https://restcountries.eu/data/bes.svg",
    callingCodes: ["+5997"],
    currencyCode: "USD",
  },
  {
    name: "Bosnia and Herzegovina",
    alpha2Code: "BA",
    emoji: "🇧🇦",
    flag: "https://restcountries.eu/data/bih.svg",
    callingCodes: ["+387"],
    currencyCode: "BAM",
  },
  {
    name: "Botswana",
    alpha2Code: "BW",
    emoji: "🇧🇼",
    flag: "https://restcountries.eu/data/bwa.svg",
    callingCodes: ["+267"],
    currencyCode: "BWP",
  },
  {
    name: "Bouvet Island",
    alpha2Code: "BV",
    emoji: "🇧🇻",
    flag: "https://restcountries.eu/data/bvt.svg",
    callingCodes: ["+"],
    currencyCode: "NOK",
  },
  {
    name: "Brazil",
    alpha2Code: "BR",
    emoji: "🇧🇷",
    flag: "https://restcountries.eu/data/bra.svg",
    callingCodes: ["+55"],
    currencyCode: "BRL",
  },
  {
    name: "British Indian Ocean Territory",
    alpha2Code: "IO",
    emoji: "🇮🇴",
    flag: "https://restcountries.eu/data/iot.svg",
    callingCodes: ["+246"],
    currencyCode: "USD",
  },
  {
    name: "Virgin Islands (British)",
    alpha2Code: "VG",
    emoji: "🇻🇬",
    flag: "https://restcountries.eu/data/vgb.svg",
    callingCodes: ["+1284"],
    currencyCode: "USD",
  },
  {
    name: "Virgin Islands (U.S.)",
    alpha2Code: "VI",
    emoji: "🇻🇮",
    flag: "https://restcountries.eu/data/vir.svg",
    callingCodes: ["+1 +340"],
    currencyCode: "USD",
  },
  {
    name: "Brunei Darussalam",
    alpha2Code: "BN",
    emoji: "🇧🇳",
    flag: "https://restcountries.eu/data/brn.svg",
    callingCodes: ["+673"],
    currencyCode: "BND",
  },
  {
    name: "Bulgaria",
    alpha2Code: "BG",
    emoji: "🇧🇬",
    flag: "https://restcountries.eu/data/bgr.svg",
    callingCodes: ["+359"],
    currencyCode: "BGN",
  },
  {
    name: "Burkina Faso",
    alpha2Code: "BF",
    emoji: "🇧🇫",
    flag: "https://restcountries.eu/data/bfa.svg",
    callingCodes: ["+226"],
    currencyCode: "XOF",
  },
  {
    name: "Burundi",
    alpha2Code: "BI",
    emoji: "🇧🇮",
    flag: "https://restcountries.eu/data/bdi.svg",
    callingCodes: ["+257"],
    currencyCode: "BIF",
  },
  {
    name: "Cambodia",
    alpha2Code: "KH",
    emoji: "🇰🇭",
    flag: "https://restcountries.eu/data/khm.svg",
    callingCodes: ["+855"],
    currencyCode: "KHR",
  },
  {
    name: "Cameroon",
    alpha2Code: "CM",
    emoji: "🇨🇲",
    flag: "https://restcountries.eu/data/cmr.svg",
    callingCodes: ["+237"],
    currencyCode: "XAF",
  },
  {
    name: "Canada",
    alpha2Code: "CA",
    emoji: "🇨🇦",
    flag: "https://restcountries.eu/data/can.svg",
    callingCodes: ["+1"],
    currencyCode: "CAD",
  },
  {
    name: "Cape Verde",
    alpha2Code: "CV",
    emoji: "🇨🇻",
    flag: "https://restcountries.eu/data/cpv.svg",
    callingCodes: ["+238"],
    currencyCode: "CVE",
  },
  {
    name: "Cayman Islands",
    alpha2Code: "KY",
    emoji: "🇰🇾",
    flag: "https://restcountries.eu/data/cym.svg",
    callingCodes: ["+1345"],
    currencyCode: "KYD",
  },
  {
    name: "Central African Republic",
    alpha2Code: "CF",
    emoji: "🇨🇫",
    flag: "https://restcountries.eu/data/caf.svg",
    callingCodes: ["+236"],
    currencyCode: "XAF",
  },
  {
    name: "Chad",
    alpha2Code: "TD",
    emoji: "🇹🇩",
    flag: "https://restcountries.eu/data/tcd.svg",
    callingCodes: ["+235"],
    currencyCode: "XAF",
  },
  {
    name: "Chile",
    alpha2Code: "CL",
    emoji: "🇨🇱",
    flag: "https://restcountries.eu/data/chl.svg",
    callingCodes: ["+56"],
    currencyCode: "CLP",
  },
  {
    name: "China",
    alpha2Code: "CN",
    emoji: "🇨🇳",
    flag: "https://restcountries.eu/data/chn.svg",
    callingCodes: ["+86"],
    currencyCode: "CNY",
  },
  {
    name: "Christmas Island",
    alpha2Code: "CX",
    emoji: "🇨🇽",
    flag: "https://restcountries.eu/data/cxr.svg",
    callingCodes: ["+61"],
    currencyCode: "AUD",
  },
  {
    name: "Cocos (Keeling) Islands",
    alpha2Code: "CC",
    emoji: "🇨🇨",
    flag: "https://restcountries.eu/data/cck.svg",
    callingCodes: ["+61"],
    currencyCode: "AUD",
  },
  {
    name: "Colombia",
    alpha2Code: "CO",
    emoji: "🇨🇴",
    flag: "https://restcountries.eu/data/col.svg",
    callingCodes: ["+57"],
    currencyCode: "COP",
  },
  {
    name: "Comoros",
    alpha2Code: "KM",
    emoji: "🇰🇲",
    flag: "https://restcountries.eu/data/com.svg",
    callingCodes: ["+269"],
    currencyCode: "KMF",
  },
  {
    name: "Congo (Republic)",
    alpha2Code: "CG",
    emoji: "🇨🇬",
    flag: "https://restcountries.eu/data/cog.svg",
    callingCodes: ["+242"],
    currencyCode: "XAF",
  },
  {
    name: "Congo (Democratic Republic)",
    alpha2Code: "CD",
    emoji: "🇨🇩",
    flag: "https://restcountries.eu/data/cod.svg",
    callingCodes: ["+243"],
    currencyCode: "CDF",
  },
  {
    name: "Cook Islands",
    alpha2Code: "CK",
    emoji: "🇨🇰",
    flag: "https://restcountries.eu/data/cok.svg",
    callingCodes: ["+682"],
    currencyCode: "NZD",
  },
  {
    name: "Costa Rica",
    alpha2Code: "CR",
    emoji: "🇨🇷",
    flag: "https://restcountries.eu/data/cri.svg",
    callingCodes: ["+506"],
    currencyCode: "CRC",
  },
  {
    name: "Croatia",
    alpha2Code: "HR",
    emoji: "🇭🇷",
    flag: "https://restcountries.eu/data/hrv.svg",
    callingCodes: ["+385"],
    currencyCode: "HRK",
  },
  {
    name: "Cuba",
    alpha2Code: "CU",
    emoji: "🇨🇺",
    flag: "https://restcountries.eu/data/cub.svg",
    callingCodes: ["+53"],
    currencyCode: "CUP",
  },
  {
    name: "Curacao",
    alpha2Code: "CW",
    emoji: "🇨🇼",
    flag: "https://restcountries.eu/data/cuw.svg",
    callingCodes: ["+599"],
    currencyCode: "ANG",
  },
  {
    name: "Cyprus",
    alpha2Code: "CY",
    emoji: "🇨🇾",
    flag: "https://restcountries.eu/data/cyp.svg",
    callingCodes: ["+357"],
    currencyCode: "EUR",
  },
  {
    name: "Czech Republic",
    alpha2Code: "CZ",
    emoji: "🇨🇿",
    flag: "https://restcountries.eu/data/cze.svg",
    callingCodes: ["+420"],
    currencyCode: "CZK",
  },
  {
    name: "Denmark",
    alpha2Code: "DK",
    emoji: "🇩🇰",
    flag: "https://restcountries.eu/data/dnk.svg",
    callingCodes: ["+45"],
    currencyCode: "DKK",
  },
  {
    name: "Djibouti",
    alpha2Code: "DJ",
    emoji: "🇩🇯",
    flag: "https://restcountries.eu/data/dji.svg",
    callingCodes: ["+253"],
    currencyCode: "DJF",
  },
  {
    name: "Dominica",
    alpha2Code: "DM",
    emoji: "🇩🇲",
    flag: "https://restcountries.eu/data/dma.svg",
    callingCodes: ["+1767"],
    currencyCode: "XCD",
  },
  {
    name: "Dominican Republic",
    alpha2Code: "DO",
    emoji: "🇩🇴",
    flag: "https://restcountries.eu/data/dom.svg",
    callingCodes: ["+1809", "+1829", "+1849"],
    currencyCode: "DOP",
  },
  {
    name: "Ecuador",
    alpha2Code: "EC",
    emoji: "🇪🇨",
    flag: "https://restcountries.eu/data/ecu.svg",
    callingCodes: ["+593"],
    currencyCode: "USD",
  },
  {
    name: "Egypt",
    alpha2Code: "EG",
    emoji: "🇪🇬",
    flag: "https://restcountries.eu/data/egy.svg",
    callingCodes: ["+20"],
    currencyCode: "EGP",
  },
  {
    name: "El Salvador",
    alpha2Code: "SV",
    emoji: "🇸🇻",
    flag: "https://restcountries.eu/data/slv.svg",
    callingCodes: ["+503"],
    currencyCode: "USD",
  },
  {
    name: "Equatorial Guinea",
    alpha2Code: "GQ",
    emoji: "🇬🇶",
    flag: "https://restcountries.eu/data/gnq.svg",
    callingCodes: ["+240"],
    currencyCode: "XAF",
  },
  {
    name: "Eritrea",
    alpha2Code: "ER",
    emoji: "🇪🇷",
    flag: "https://restcountries.eu/data/eri.svg",
    callingCodes: ["+291"],
    currencyCode: "ERN",
  },
  {
    name: "Estonia",
    alpha2Code: "EE",
    emoji: "🇪🇪",
    flag: "https://restcountries.eu/data/est.svg",
    callingCodes: ["+372"],
    currencyCode: "EUR",
  },
  {
    name: "Ethiopia",
    alpha2Code: "ET",
    emoji: "🇪🇹",
    flag: "https://restcountries.eu/data/eth.svg",
    callingCodes: ["+251"],
    currencyCode: "ETB",
  },
  {
    name: "Falkland Islands (Malvinas)",
    alpha2Code: "FK",
    emoji: "🇫🇰",
    flag: "https://restcountries.eu/data/flk.svg",
    callingCodes: ["+500"],
    currencyCode: "FKP",
  },
  {
    name: "Faroe Islands",
    alpha2Code: "FO",
    emoji: "🇫🇴",
    flag: "https://restcountries.eu/data/fro.svg",
    callingCodes: ["+298"],
    currencyCode: "DKK",
  },
  {
    name: "Fiji",
    alpha2Code: "FJ",
    emoji: "🇫🇯",
    flag: "https://restcountries.eu/data/fji.svg",
    callingCodes: ["+679"],
    currencyCode: "FJD",
  },
  {
    name: "Finland",
    alpha2Code: "FI",
    emoji: "🇫🇮",
    flag: "https://restcountries.eu/data/fin.svg",
    callingCodes: ["+358"],
    currencyCode: "EUR",
  },
  {
    name: "France",
    alpha2Code: "FR",
    emoji: "🇫🇷",
    flag: "https://restcountries.eu/data/fra.svg",
    callingCodes: ["+33"],
    currencyCode: "EUR",
  },
  {
    name: "French Guiana",
    alpha2Code: "GF",
    emoji: "🇬🇫",
    flag: "https://restcountries.eu/data/guf.svg",
    callingCodes: ["+594"],
    currencyCode: "EUR",
  },
  {
    name: "French Polynesia",
    alpha2Code: "PF",
    emoji: "🇵🇫",
    flag: "https://restcountries.eu/data/pyf.svg",
    callingCodes: ["+689"],
    currencyCode: "XPF",
  },
  {
    name: "Gabon",
    alpha2Code: "GA",
    emoji: "🇬🇦",
    flag: "https://restcountries.eu/data/gab.svg",
    callingCodes: ["+241"],
    currencyCode: "XAF",
  },
  {
    name: "Gambia",
    alpha2Code: "GM",
    emoji: "🇬🇲",
    flag: "https://restcountries.eu/data/gmb.svg",
    callingCodes: ["+220"],
    currencyCode: "GMD",
  },
  {
    name: "Georgia",
    alpha2Code: "GE",
    emoji: "🇬🇪",
    flag: "https://restcountries.eu/data/geo.svg",
    callingCodes: ["+995"],
    currencyCode: "GEL",
  },
  {
    name: "Germany",
    alpha2Code: "DE",
    emoji: "🇩🇪",
    flag: "https://restcountries.eu/data/deu.svg",
    callingCodes: ["+49"],
    currencyCode: "EUR",
  },
  {
    name: "Ghana",
    alpha2Code: "GH",
    emoji: "🇬🇭",
    flag: "https://restcountries.eu/data/gha.svg",
    callingCodes: ["+233"],
    currencyCode: "GHS",
  },
  {
    name: "Gibraltar",
    alpha2Code: "GI",
    emoji: "🇬🇮",
    flag: "https://restcountries.eu/data/gib.svg",
    callingCodes: ["+350"],
    currencyCode: "GIP",
  },
  {
    name: "Greece",
    alpha2Code: "GR",
    emoji: "🇬🇷",
    flag: "https://restcountries.eu/data/grc.svg",
    callingCodes: ["+30"],
    currencyCode: "EUR",
  },
  {
    name: "Greenland",
    alpha2Code: "GL",
    emoji: "🇬🇱",
    flag: "https://restcountries.eu/data/grl.svg",
    callingCodes: ["+299"],
    currencyCode: "DKK",
  },
  {
    name: "Grenada",
    alpha2Code: "GD",
    emoji: "🇬🇩",
    flag: "https://restcountries.eu/data/grd.svg",
    callingCodes: ["+1473"],
    currencyCode: "XCD",
  },
  {
    name: "Guadeloupe",
    alpha2Code: "GP",
    emoji: "🇬🇵",
    flag: "https://restcountries.eu/data/glp.svg",
    callingCodes: ["+590"],
    currencyCode: "EUR",
  },
  {
    name: "Guam",
    alpha2Code: "GU",
    emoji: "🇬🇺",
    flag: "https://restcountries.eu/data/gum.svg",
    callingCodes: ["+1671"],
    currencyCode: "USD",
  },
  {
    name: "Guatemala",
    alpha2Code: "GT",
    emoji: "🇬🇹",
    flag: "https://restcountries.eu/data/gtm.svg",
    callingCodes: ["+502"],
    currencyCode: "GTQ",
  },
  {
    name: "Guernsey",
    alpha2Code: "GG",
    emoji: "🇬🇬",
    flag: "https://restcountries.eu/data/ggy.svg",
    callingCodes: ["+44"],
    currencyCode: "GBP",
  },
  {
    name: "Guinea",
    alpha2Code: "GN",
    emoji: "🇬🇳",
    flag: "https://restcountries.eu/data/gin.svg",
    callingCodes: ["+224"],
    currencyCode: "GNF",
  },
  {
    name: "Guinea-Bissau",
    alpha2Code: "GW",
    emoji: "🇬🇼",
    flag: "https://restcountries.eu/data/gnb.svg",
    callingCodes: ["+245"],
    currencyCode: "XOF",
  },
  {
    name: "Guyana",
    alpha2Code: "GY",
    emoji: "🇬🇾",
    flag: "https://restcountries.eu/data/guy.svg",
    callingCodes: ["+592"],
    currencyCode: "GYD",
  },
  {
    name: "Haiti",
    alpha2Code: "HT",
    emoji: "🇭🇹",
    flag: "https://restcountries.eu/data/hti.svg",
    callingCodes: ["+509"],
    currencyCode: "HTG",
  },
  {
    name: "Vatican city",
    alpha2Code: "VA",
    emoji: "🇻🇦",
    flag: "https://restcountries.eu/data/vat.svg",
    callingCodes: ["+379"],
    currencyCode: "EUR",
  },
  {
    name: "Honduras",
    alpha2Code: "HN",
    emoji: "🇭🇳",
    flag: "https://restcountries.eu/data/hnd.svg",
    callingCodes: ["+504"],
    currencyCode: "HNL",
  },
  {
    name: "Hong Kong",
    alpha2Code: "HK",
    emoji: "🇭🇰",
    flag: "https://restcountries.eu/data/hkg.svg",
    callingCodes: ["+852"],
    currencyCode: "HKD",
  },
  {
    name: "Hungary",
    alpha2Code: "HU",
    emoji: "🇭🇺",
    flag: "https://restcountries.eu/data/hun.svg",
    callingCodes: ["+36"],
    currencyCode: "HUF",
  },
  {
    name: "Iceland",
    alpha2Code: "IS",
    emoji: "🇮🇸",
    flag: "https://restcountries.eu/data/isl.svg",
    callingCodes: ["+354"],
    currencyCode: "ISK",
  },
  {
    name: "India",
    alpha2Code: "IN",
    emoji: "🇮🇳",
    flag: "https://restcountries.eu/data/ind.svg",
    callingCodes: ["+91"],
    currencyCode: "INR",
  },
  {
    name: "Indonesia",
    alpha2Code: "ID",
    emoji: "🇮🇩",
    flag: "https://restcountries.eu/data/idn.svg",
    callingCodes: ["+62"],
    currencyCode: "IDR",
  },
  {
    name: "Côte d'Ivoire",
    alpha2Code: "CI",
    emoji: "🇨🇮",
    flag: "https://restcountries.eu/data/civ.svg",
    callingCodes: ["+225"],
    currencyCode: "XOF",
  },
  {
    name: "Iran",
    alpha2Code: "IR",
    emoji: "🇮🇷",
    flag: "https://restcountries.eu/data/irn.svg",
    callingCodes: ["+98"],
    currencyCode: "IRR",
  },
  {
    name: "Iraq",
    alpha2Code: "IQ",
    emoji: "🇮🇶",
    flag: "https://restcountries.eu/data/irq.svg",
    callingCodes: ["+964"],
    currencyCode: "IQD",
  },
  {
    name: "Ireland",
    alpha2Code: "IE",
    emoji: "🇮🇪",
    flag: "https://restcountries.eu/data/irl.svg",
    callingCodes: ["+353"],
    currencyCode: "EUR",
  },
  {
    name: "Isle of Man",
    alpha2Code: "IM",
    emoji: "🇮🇲",
    flag: "https://restcountries.eu/data/imn.svg",
    callingCodes: ["+44"],
    currencyCode: "GBP",
  },
  {
    name: "Israel",
    alpha2Code: "IL",
    emoji: "🇮🇱",
    flag: "https://restcountries.eu/data/isr.svg",
    callingCodes: ["+972"],
    currencyCode: "ILS",
  },
  {
    name: "Italy",
    alpha2Code: "IT",
    emoji: "🇮🇹",
    flag: "https://restcountries.eu/data/ita.svg",
    callingCodes: ["+39"],
    currencyCode: "EUR",
  },
  {
    name: "Jamaica",
    alpha2Code: "JM",
    emoji: "🇯🇲",
    flag: "https://restcountries.eu/data/jam.svg",
    callingCodes: ["+1876"],
    currencyCode: "JMD",
  },
  {
    name: "Japan",
    alpha2Code: "JP",
    emoji: "🇯🇵",
    flag: "https://restcountries.eu/data/jpn.svg",
    callingCodes: ["+81"],
    currencyCode: "JPY",
  },
  {
    name: "Jersey",
    alpha2Code: "JE",
    emoji: "🇯🇪",
    flag: "https://restcountries.eu/data/jey.svg",
    callingCodes: ["+44"],
    currencyCode: "GBP",
  },
  {
    name: "Jordan",
    alpha2Code: "JO",
    emoji: "🇯🇴",
    flag: "https://restcountries.eu/data/jor.svg",
    callingCodes: ["+962"],
    currencyCode: "JOD",
  },
  {
    name: "Kazakhstan",
    alpha2Code: "KZ",
    emoji: "🇰🇿",
    flag: "https://restcountries.eu/data/kaz.svg",
    callingCodes: ["+76", "+77"],
    currencyCode: "KZT",
  },
  {
    name: "Kenya",
    alpha2Code: "KE",
    emoji: "🇰🇪",
    flag: "https://restcountries.eu/data/ken.svg",
    callingCodes: ["+254"],
    currencyCode: "KES",
  },
  {
    name: "Kiribati",
    alpha2Code: "KI",
    emoji: "🇰🇮",
    flag: "https://restcountries.eu/data/kir.svg",
    callingCodes: ["+686"],
    currencyCode: "AUD",
  },
  {
    name: "Kuwait",
    alpha2Code: "KW",
    emoji: "🇰🇼",
    flag: "https://restcountries.eu/data/kwt.svg",
    callingCodes: ["+965"],
    currencyCode: "KWD",
  },
  {
    name: "Kyrgyzstan",
    alpha2Code: "KG",
    emoji: "🇰🇬",
    flag: "https://restcountries.eu/data/kgz.svg",
    callingCodes: ["+996"],
    currencyCode: "KGS",
  },
  {
    name: "Laos",
    alpha2Code: "LA",
    emoji: "🇱🇦",
    flag: "https://restcountries.eu/data/lao.svg",
    callingCodes: ["+856"],
    currencyCode: "LAK",
  },
  {
    name: "Latvia",
    alpha2Code: "LV",
    emoji: "🇱🇻",
    flag: "https://restcountries.eu/data/lva.svg",
    callingCodes: ["+371"],
    currencyCode: "EUR",
  },
  {
    name: "Lebanon",
    alpha2Code: "LB",
    emoji: "🇱🇧",
    flag: "https://restcountries.eu/data/lbn.svg",
    callingCodes: ["+961"],
    currencyCode: "LBP",
  },
  {
    name: "Lesotho",
    alpha2Code: "LS",
    emoji: "🇱🇸",
    flag: "https://restcountries.eu/data/lso.svg",
    callingCodes: ["+266"],
    currencyCode: "LSL",
  },
  {
    name: "Liberia",
    alpha2Code: "LR",
    emoji: "🇱🇷",
    flag: "https://restcountries.eu/data/lbr.svg",
    callingCodes: ["+231"],
    currencyCode: "LRD",
  },
  {
    name: "Libya",
    alpha2Code: "LY",
    emoji: "🇱🇾",
    flag: "https://restcountries.eu/data/lby.svg",
    callingCodes: ["+218"],
    currencyCode: "LYD",
  },
  {
    name: "Liechtenstein",
    alpha2Code: "LI",
    emoji: "🇱🇮",
    flag: "https://restcountries.eu/data/lie.svg",
    callingCodes: ["+423"],
    currencyCode: "CHF",
  },
  {
    name: "Lithuania",
    alpha2Code: "LT",
    emoji: "🇱🇹",
    flag: "https://restcountries.eu/data/ltu.svg",
    callingCodes: ["+370"],
    currencyCode: "EUR",
  },
  {
    name: "Macao",
    alpha2Code: "MO",
    emoji: "🇲🇴",
    flag: "https://restcountries.eu/data/mac.svg",
    callingCodes: ["+853"],
    currencyCode: "MOP",
  },
  {
    name: "Macedonia",
    alpha2Code: "MK",
    emoji: "🇲🇰",
    flag: "https://restcountries.eu/data/mkd.svg",
    callingCodes: ["+389"],
    currencyCode: "MKD",
  },
  {
    name: "Madagascar",
    alpha2Code: "MG",
    emoji: "🇲🇬",
    flag: "https://restcountries.eu/data/mdg.svg",
    callingCodes: ["+261"],
    currencyCode: "MGA",
  },
  {
    name: "Malawi",
    alpha2Code: "MW",
    emoji: "🇲🇼",
    flag: "https://restcountries.eu/data/mwi.svg",
    callingCodes: ["+265"],
    currencyCode: "MWK",
  },
  {
    name: "Malaysia",
    alpha2Code: "MY",
    emoji: "🇲🇾",
    flag: "https://restcountries.eu/data/mys.svg",
    callingCodes: ["+60"],
    currencyCode: "MYR",
  },
  {
    name: "Maldives",
    alpha2Code: "MV",
    emoji: "🇲🇻",
    flag: "https://restcountries.eu/data/mdv.svg",
    callingCodes: ["+960"],
    currencyCode: "MVR",
  },
  {
    name: "Mali",
    alpha2Code: "ML",
    emoji: "🇲🇱",
    flag: "https://restcountries.eu/data/mli.svg",
    callingCodes: ["+223"],
    currencyCode: "XOF",
  },
  {
    name: "Malta",
    alpha2Code: "MT",
    emoji: "🇲🇹",
    flag: "https://restcountries.eu/data/mlt.svg",
    callingCodes: ["+356"],
    currencyCode: "EUR",
  },
  {
    name: "Marshall Islands",
    alpha2Code: "MH",
    emoji: "🇲🇭",
    flag: "https://restcountries.eu/data/mhl.svg",
    callingCodes: ["+692"],
    currencyCode: "USD",
  },
  {
    name: "Martinique",
    alpha2Code: "MQ",
    emoji: "🇲🇶",
    flag: "https://restcountries.eu/data/mtq.svg",
    callingCodes: ["+596"],
    currencyCode: "EUR",
  },
  {
    name: "Mauritania",
    alpha2Code: "MR",
    emoji: "🇲🇷",
    flag: "https://restcountries.eu/data/mrt.svg",
    callingCodes: ["+222"],
    currencyCode: "MRO",
  },
  {
    name: "Mauritius",
    alpha2Code: "MU",
    emoji: "🇲🇺",
    flag: "https://restcountries.eu/data/mus.svg",
    callingCodes: ["+230"],
    currencyCode: "MUR",
  },
  {
    name: "Mayotte",
    alpha2Code: "YT",
    emoji: "🇾🇹",
    flag: "https://restcountries.eu/data/myt.svg",
    callingCodes: ["+262"],
    currencyCode: "EUR",
  },
  {
    name: "Mexico",
    alpha2Code: "MX",
    emoji: "🇲🇽",
    flag: "https://restcountries.eu/data/mex.svg",
    callingCodes: ["+52"],
    currencyCode: "MXN",
  },
  {
    name: "Micronesia (Federated States)",
    alpha2Code: "FM",
    emoji: "🇫🇲",
    flag: "https://restcountries.eu/data/fsm.svg",
    callingCodes: ["+691"],
    currencyCode: "USD",
  },
  {
    name: "Moldova",
    alpha2Code: "MD",
    emoji: "🇲🇩",
    flag: "https://restcountries.eu/data/mda.svg",
    callingCodes: ["+373"],
    currencyCode: "MDL",
  },
  {
    name: "Monaco",
    alpha2Code: "MC",
    emoji: "🇲🇨",
    flag: "https://restcountries.eu/data/mco.svg",
    callingCodes: ["+377"],
    currencyCode: "EUR",
  },
  {
    name: "Mongolia",
    alpha2Code: "MN",
    emoji: "🇲🇳",
    flag: "https://restcountries.eu/data/mng.svg",
    callingCodes: ["+976"],
    currencyCode: "MNT",
  },
  {
    name: "Montenegro",
    alpha2Code: "ME",
    emoji: "🇲🇪",
    flag: "https://restcountries.eu/data/mne.svg",
    callingCodes: ["+382"],
    currencyCode: "EUR",
  },
  {
    name: "Montserrat",
    alpha2Code: "MS",
    emoji: "🇲🇸",
    flag: "https://restcountries.eu/data/msr.svg",
    callingCodes: ["+1664"],
    currencyCode: "XCD",
  },
  {
    name: "Morocco",
    alpha2Code: "MA",
    emoji: "🇲🇦",
    flag: "https://restcountries.eu/data/mar.svg",
    callingCodes: ["+212"],
    currencyCode: "MAD",
  },
  {
    name: "Mozambique",
    alpha2Code: "MZ",
    emoji: "🇲🇿",
    flag: "https://restcountries.eu/data/moz.svg",
    callingCodes: ["+258"],
    currencyCode: "MZN",
  },
  {
    name: "Myanmar (Burma)",
    alpha2Code: "MM",
    emoji: "🇲🇲",
    flag: "https://restcountries.eu/data/mmr.svg",
    callingCodes: ["+95"],
    currencyCode: "MMK",
  },
  {
    name: "Namibia",
    alpha2Code: "NA",
    emoji: "🇳🇦",
    flag: "https://restcountries.eu/data/nam.svg",
    callingCodes: ["+264"],
    currencyCode: "NAD",
  },
  {
    name: "Nauru",
    alpha2Code: "NR",
    emoji: "🇳🇷",
    flag: "https://restcountries.eu/data/nru.svg",
    callingCodes: ["+674"],
    currencyCode: "AUD",
  },
  {
    name: "Nepal",
    alpha2Code: "NP",
    emoji: "🇳🇵",
    flag: "https://restcountries.eu/data/npl.svg",
    callingCodes: ["+977"],
    currencyCode: "NPR",
  },
  {
    name: "Netherlands",
    alpha2Code: "NL",
    emoji: "🇳🇱",
    flag: "https://restcountries.eu/data/nld.svg",
    callingCodes: ["+31"],
    currencyCode: "EUR",
  },
  {
    name: "New Caledonia",
    alpha2Code: "NC",
    emoji: "🇳🇨",
    flag: "https://restcountries.eu/data/ncl.svg",
    callingCodes: ["+687"],
    currencyCode: "XPF",
  },
  {
    name: "New Zealand",
    alpha2Code: "NZ",
    emoji: "🇳🇿",
    flag: "https://restcountries.eu/data/nzl.svg",
    callingCodes: ["+64"],
    currencyCode: "NZD",
  },
  {
    name: "Nicaragua",
    alpha2Code: "NI",
    emoji: "🇳🇮",
    flag: "https://restcountries.eu/data/nic.svg",
    callingCodes: ["+505"],
    currencyCode: "NIO",
  },
  {
    name: "Niger",
    alpha2Code: "NE",
    emoji: "🇳🇪",
    flag: "https://restcountries.eu/data/ner.svg",
    callingCodes: ["+227"],
    currencyCode: "XOF",
  },
  {
    name: "Nigeria",
    alpha2Code: "NG",
    emoji: "🇳🇬",
    flag: "https://restcountries.eu/data/nga.svg",
    callingCodes: ["+234"],
    currencyCode: "NGN",
  },
  {
    name: "Niue",
    alpha2Code: "NU",
    emoji: "🇳🇺",
    flag: "https://restcountries.eu/data/niu.svg",
    callingCodes: ["+683"],
    currencyCode: "NZD",
  },
  {
    name: "Norfolk Island",
    alpha2Code: "NF",
    emoji: "🇳🇫",
    flag: "https://restcountries.eu/data/nfk.svg",
    callingCodes: ["+672"],
    currencyCode: "AUD",
  },
  {
    name: "North Korea",
    alpha2Code: "KP",
    emoji: "🇰🇵",
    flag: "https://restcountries.eu/data/prk.svg",
    callingCodes: ["+850"],
    currencyCode: "KPW",
  },
  {
    name: "Northern Mariana Islands",
    alpha2Code: "MP",
    emoji: "🇲🇵",
    flag: "https://restcountries.eu/data/mnp.svg",
    callingCodes: ["+1670"],
    currencyCode: "USD",
  },
  {
    name: "Norway",
    alpha2Code: "NO",
    emoji: "🇳🇴",
    flag: "https://restcountries.eu/data/nor.svg",
    callingCodes: ["+47"],
    currencyCode: "NOK",
  },
  {
    name: "Oman",
    alpha2Code: "OM",
    emoji: "🇴🇲",
    flag: "https://restcountries.eu/data/omn.svg",
    callingCodes: ["+968"],
    currencyCode: "OMR",
  },
  {
    name: "Pakistan",
    alpha2Code: "PK",
    emoji: "🇵🇰",
    flag: "https://restcountries.eu/data/pak.svg",
    callingCodes: ["+92"],
    currencyCode: "PKR",
  },
  {
    name: "Palau",
    alpha2Code: "PW",
    emoji: "🇵🇼",
    flag: "https://restcountries.eu/data/plw.svg",
    callingCodes: ["+680"],
    currencyCode: "USD",
  },
  {
    name: "Palestine",
    alpha2Code: "PS",
    emoji: "🇵🇸",
    flag: "https://restcountries.eu/data/pse.svg",
    callingCodes: ["+970"],
    currencyCode: "ILS",
  },
  {
    name: "Panama",
    alpha2Code: "PA",
    emoji: "🇵🇦",
    flag: "https://restcountries.eu/data/pan.svg",
    callingCodes: ["+507"],
    currencyCode: "PAB",
  },
  {
    name: "Papua New Guinea",
    alpha2Code: "PG",
    emoji: "🇵🇬",
    flag: "https://restcountries.eu/data/png.svg",
    callingCodes: ["+675"],
    currencyCode: "PGK",
  },
  {
    name: "Paraguay",
    alpha2Code: "PY",
    emoji: "🇵🇾",
    flag: "https://restcountries.eu/data/pry.svg",
    callingCodes: ["+595"],
    currencyCode: "PYG",
  },
  {
    name: "Peru",
    alpha2Code: "PE",
    emoji: "🇵🇪",
    flag: "https://restcountries.eu/data/per.svg",
    callingCodes: ["+51"],
    currencyCode: "PEN",
  },
  {
    name: "Philippines",
    alpha2Code: "PH",
    emoji: "🇵🇭",
    flag: "https://restcountries.eu/data/phl.svg",
    callingCodes: ["+63"],
    currencyCode: "PHP",
  },
  {
    name: "Pitcairn",
    alpha2Code: "PN",
    emoji: "🇵🇳",
    flag: "https://restcountries.eu/data/pcn.svg",
    callingCodes: ["+64"],
    currencyCode: "NZD",
  },
  {
    name: "Poland",
    alpha2Code: "PL",
    emoji: "🇵🇱",
    flag: "https://restcountries.eu/data/pol.svg",
    callingCodes: ["+48"],
    currencyCode: "PLN",
  },
  {
    name: "Portugal",
    alpha2Code: "PT",
    emoji: "🇵🇹",
    flag: "https://restcountries.eu/data/prt.svg",
    callingCodes: ["+351"],
    currencyCode: "EUR",
  },
  {
    name: "Puerto Rico",
    alpha2Code: "PR",
    emoji: "🇵🇷",
    flag: "https://restcountries.eu/data/pri.svg",
    callingCodes: ["+1787", "+1939"],
    currencyCode: "USD",
  },
  {
    name: "Qatar",
    alpha2Code: "QA",
    emoji: "🇶🇦",
    flag: "https://restcountries.eu/data/qat.svg",
    callingCodes: ["+974"],
    currencyCode: "QAR",
  },
  {
    name: "Kosovo",
    alpha2Code: "XK",
    emoji: "🇽🇰",
    flag: "https://restcountries.eu/data/kos.svg",
    callingCodes: ["+383"],
    currencyCode: "EUR",
  },
  {
    name: "Reunion",
    alpha2Code: "RE",
    emoji: "🇷🇪",
    flag: "https://restcountries.eu/data/reu.svg",
    callingCodes: ["+262"],
    currencyCode: "EUR",
  },
  {
    name: "Romania",
    alpha2Code: "RO",
    emoji: "🇷🇴",
    flag: "https://restcountries.eu/data/rou.svg",
    callingCodes: ["+40"],
    currencyCode: "RON",
  },
  {
    name: "Russia",
    alpha2Code: "RU",
    emoji: "🇷🇺",
    flag: "https://restcountries.eu/data/rus.svg",
    callingCodes: ["+7"],
    currencyCode: "RUB",
  },
  {
    name: "Rwanda",
    alpha2Code: "RW",
    emoji: "🇷🇼",
    flag: "https://restcountries.eu/data/rwa.svg",
    callingCodes: ["+250"],
    currencyCode: "RWF",
  },
  {
    name: "Saint Barthélemy",
    alpha2Code: "BL",
    emoji: "🇧🇱",
    flag: "https://restcountries.eu/data/blm.svg",
    callingCodes: ["+590"],
    currencyCode: "EUR",
  },
  {
    name: "Saint Helena",
    alpha2Code: "SH",
    emoji: "🇸🇭",
    flag: "https://restcountries.eu/data/shn.svg",
    callingCodes: ["+290"],
    currencyCode: "SHP",
  },
  {
    name: "Saint Kitts and Nevis",
    alpha2Code: "KN",
    emoji: "🇰🇳",
    flag: "https://restcountries.eu/data/kna.svg",
    callingCodes: ["+1869"],
    currencyCode: "XCD",
  },
  {
    name: "Saint Lucia",
    alpha2Code: "LC",
    emoji: "🇱🇨",
    flag: "https://restcountries.eu/data/lca.svg",
    callingCodes: ["+1758"],
    currencyCode: "XCD",
  },
  {
    name: "Saint Martin",
    alpha2Code: "MF",
    emoji: "🇲🇫",
    flag: "https://restcountries.eu/data/maf.svg",
    callingCodes: ["+590"],
    currencyCode: "EUR",
  },
  {
    name: "Saint Pierre and Miquelon",
    alpha2Code: "PM",
    emoji: "🇵🇲",
    flag: "https://restcountries.eu/data/spm.svg",
    callingCodes: ["+508"],
    currencyCode: "EUR",
  },
  {
    name: "Saint Vincent and the Grenadines",
    alpha2Code: "VC",
    emoji: "🇻🇨",
    flag: "https://restcountries.eu/data/vct.svg",
    callingCodes: ["+1784"],
    currencyCode: "XCD",
  },
  {
    name: "Samoa",
    alpha2Code: "WS",
    emoji: "🇼🇸",
    flag: "https://restcountries.eu/data/wsm.svg",
    callingCodes: ["+685"],
    currencyCode: "WST",
  },
  {
    name: "San Marino",
    alpha2Code: "SM",
    emoji: "🇸🇲",
    flag: "https://restcountries.eu/data/smr.svg",
    callingCodes: ["+378"],
    currencyCode: "EUR",
  },
  {
    name: "Sao Tome and Principe",
    alpha2Code: "ST",
    emoji: "🇸🇹",
    flag: "https://restcountries.eu/data/stp.svg",
    callingCodes: ["+239"],
    currencyCode: "STD",
  },
  {
    name: "Saudi Arabia",
    alpha2Code: "SA",
    emoji: "🇸🇦",
    flag: "https://restcountries.eu/data/sau.svg",
    callingCodes: ["+966"],
    currencyCode: "SAR",
  },
  {
    name: "Senegal",
    alpha2Code: "SN",
    emoji: "🇸🇳",
    flag: "https://restcountries.eu/data/sen.svg",
    callingCodes: ["+221"],
    currencyCode: "XOF",
  },
  {
    name: "Serbia",
    alpha2Code: "RS",
    emoji: "🇷🇸",
    flag: "https://restcountries.eu/data/srb.svg",
    callingCodes: ["+381"],
    currencyCode: "RSD",
  },
  {
    name: "Seychelles",
    alpha2Code: "SC",
    emoji: "🇸🇨",
    flag: "https://restcountries.eu/data/syc.svg",
    callingCodes: ["+248"],
    currencyCode: "SCR",
  },
  {
    name: "Sierra Leone",
    alpha2Code: "SL",
    emoji: "🇸🇱",
    flag: "https://restcountries.eu/data/sle.svg",
    callingCodes: ["+232"],
    currencyCode: "SLL",
  },
  {
    name: "Singapore",
    alpha2Code: "SG",
    emoji: "🇸🇬",
    flag: "https://restcountries.eu/data/sgp.svg",
    callingCodes: ["+65"],
    currencyCode: "SGD",
  },
  {
    name: "Sint Maarten",
    alpha2Code: "SX",
    emoji: "🇸🇽",
    flag: "https://restcountries.eu/data/sxm.svg",
    callingCodes: ["+1721"],
    currencyCode: "ANG",
  },
  {
    name: "Slovakia",
    alpha2Code: "SK",
    emoji: "🇸🇰",
    flag: "https://restcountries.eu/data/svk.svg",
    callingCodes: ["+421"],
    currencyCode: "EUR",
  },
  {
    name: "Slovenia",
    alpha2Code: "SI",
    emoji: "🇸🇮",
    flag: "https://restcountries.eu/data/svn.svg",
    callingCodes: ["+386"],
    currencyCode: "EUR",
  },
  {
    name: "Solomon Islands",
    alpha2Code: "SB",
    emoji: "🇸🇧",
    flag: "https://restcountries.eu/data/slb.svg",
    callingCodes: ["+677"],
    currencyCode: "SBD",
  },
  {
    name: "Somalia",
    alpha2Code: "SO",
    emoji: "🇸🇴",
    flag: "https://restcountries.eu/data/som.svg",
    callingCodes: ["+252"],
    currencyCode: "SOS",
  },
  {
    name: "South Africa",
    alpha2Code: "ZA",
    emoji: "🇿🇦",
    flag: "https://restcountries.eu/data/zaf.svg",
    callingCodes: ["+27"],
    currencyCode: "ZAR",
  },
  {
    name: "South Korea",
    alpha2Code: "KR",
    emoji: "🇰🇷",
    flag: "https://restcountries.eu/data/kor.svg",
    callingCodes: ["+82"],
    currencyCode: "KRW",
  },
  {
    name: "South Sudan",
    alpha2Code: "SS",
    emoji: "🇸🇸",
    flag: "https://restcountries.eu/data/ssd.svg",
    callingCodes: ["+211"],
    currencyCode: "SSP",
  },
  {
    name: "Spain",
    alpha2Code: "ES",
    emoji: "🇪🇸",
    flag: "https://restcountries.eu/data/esp.svg",
    callingCodes: ["+34"],
    currencyCode: "EUR",
  },
  {
    name: "Sri Lanka",
    alpha2Code: "LK",
    emoji: "🇱🇰",
    flag: "https://restcountries.eu/data/lka.svg",
    callingCodes: ["+94"],
    currencyCode: "LKR",
  },
  {
    name: "Sudan",
    alpha2Code: "SD",
    emoji: "🇸🇩",
    flag: "https://restcountries.eu/data/sdn.svg",
    callingCodes: ["+249"],
    currencyCode: "SDG",
  },
  {
    name: "Suriname",
    alpha2Code: "SR",
    emoji: "🇸🇷",
    flag: "https://restcountries.eu/data/sur.svg",
    callingCodes: ["+597"],
    currencyCode: "SRD",
  },
  {
    name: "Svalbard and Jan Mayen",
    alpha2Code: "SJ",
    emoji: "🇸🇯",
    flag: "https://restcountries.eu/data/sjm.svg",
    callingCodes: ["+4779"],
    currencyCode: "NOK",
  },
  {
    name: "Swaziland (Eswatini)",
    alpha2Code: "SZ",
    emoji: "🇸🇿",
    flag: "https://restcountries.eu/data/swz.svg",
    callingCodes: ["+268"],
    currencyCode: "SZL",
  },
  {
    name: "Sweden",
    alpha2Code: "SE",
    emoji: "🇸🇪",
    flag: "https://restcountries.eu/data/swe.svg",
    callingCodes: ["+46"],
    currencyCode: "SEK",
  },
  {
    name: "Switzerland",
    alpha2Code: "CH",
    emoji: "🇨🇭",
    flag: "https://restcountries.eu/data/che.svg",
    callingCodes: ["+41"],
    currencyCode: "CHF",
  },
  {
    name: "Syria",
    alpha2Code: "SY",
    emoji: "🇸🇾",
    flag: "https://restcountries.eu/data/syr.svg",
    callingCodes: ["+963"],
    currencyCode: "SYP",
  },
  {
    name: "Taiwan",
    alpha2Code: "TW",
    emoji: "🇹🇼",
    flag: "https://restcountries.eu/data/twn.svg",
    callingCodes: ["+886"],
    currencyCode: "TWD",
  },
  {
    name: "Tajikistan",
    alpha2Code: "TJ",
    emoji: "🇹🇯",
    flag: "https://restcountries.eu/data/tjk.svg",
    callingCodes: ["+992"],
    currencyCode: "TJS",
  },
  {
    name: "Tanzania, United Republic of",
    alpha2Code: "TZ",
    emoji: "🇹🇿",
    flag: "https://restcountries.eu/data/tza.svg",
    callingCodes: ["+255"],
    currencyCode: "TZS",
  },
  {
    name: "Thailand",
    alpha2Code: "TH",
    emoji: "🇹🇭",
    flag: "https://restcountries.eu/data/tha.svg",
    callingCodes: ["+66"],
    currencyCode: "THB",
  },
  {
    name: "Timor-Leste",
    alpha2Code: "TL",
    emoji: "🇹🇱",
    flag: "https://restcountries.eu/data/tls.svg",
    callingCodes: ["+670"],
    currencyCode: "USD",
  },
  {
    name: "Togo",
    alpha2Code: "TG",
    emoji: "🇹🇬",
    flag: "https://restcountries.eu/data/tgo.svg",
    callingCodes: ["+228"],
    currencyCode: "XOF",
  },
  {
    name: "Tokelau",
    alpha2Code: "TK",
    emoji: "🇹🇰",
    flag: "https://restcountries.eu/data/tkl.svg",
    callingCodes: ["+690"],
    currencyCode: "NZD",
  },
  {
    name: "Tonga",
    alpha2Code: "TO",
    emoji: "🇹🇴",
    flag: "https://restcountries.eu/data/ton.svg",
    callingCodes: ["+676"],
    currencyCode: "TOP",
  },
  {
    name: "Trinidad and Tobago",
    alpha2Code: "TT",
    emoji: "🇹🇹",
    flag: "https://restcountries.eu/data/tto.svg",
    callingCodes: ["+1868"],
    currencyCode: "TTD",
  },
  {
    name: "Tunisia",
    alpha2Code: "TN",
    emoji: "🇹🇳",
    flag: "https://restcountries.eu/data/tun.svg",
    callingCodes: ["+216"],
    currencyCode: "TND",
  },
  {
    name: "Turkey",
    alpha2Code: "TR",
    emoji: "🇹🇷",
    flag: "https://restcountries.eu/data/tur.svg",
    callingCodes: ["+90"],
    currencyCode: "TRY",
  },
  {
    name: "Turkmenistan",
    alpha2Code: "TM",
    emoji: "🇹🇲",
    flag: "https://restcountries.eu/data/tkm.svg",
    callingCodes: ["+993"],
    currencyCode: "TMT",
  },
  {
    name: "Turks and Caicos Islands",
    alpha2Code: "TC",
    emoji: "🇹🇨",
    flag: "https://restcountries.eu/data/tca.svg",
    callingCodes: ["+1649"],
    currencyCode: "USD",
  },
  {
    name: "Tuvalu",
    alpha2Code: "TV",
    emoji: "🇹🇻",
    flag: "https://restcountries.eu/data/tuv.svg",
    callingCodes: ["+688"],
    currencyCode: "AUD",
  },
  {
    name: "Uganda",
    alpha2Code: "UG",
    emoji: "🇺🇬",
    flag: "https://restcountries.eu/data/uga.svg",
    callingCodes: ["+256"],
    currencyCode: "UGX",
  },
  {
    name: "Ukraine",
    alpha2Code: "UA",
    emoji: "🇺🇦",
    flag: "https://restcountries.eu/data/ukr.svg",
    callingCodes: ["+380"],
    currencyCode: "UAH",
  },
  {
    name: "United Arab Emirates",
    alpha2Code: "AE",
    emoji: "🇦🇪",
    flag: "https://restcountries.eu/data/are.svg",
    callingCodes: ["+971"],
    currencyCode: "AED",
  },
  {
    name: "United Kingdom (Britain)",
    alpha2Code: "GB",
    emoji: "🇬🇧",
    flag: "https://restcountries.eu/data/gbr.svg",
    callingCodes: ["+44"],
    currencyCode: "GBP",
  },
  {
    name: "United States of America",
    alpha2Code: "US",
    emoji: "🇺🇸",
    flag: "https://restcountries.eu/data/usa.svg",
    callingCodes: ["+1"],
    currencyCode: "USD",
  },
  {
    name: "Uruguay",
    alpha2Code: "UY",
    emoji: "🇺🇾",
    flag: "https://restcountries.eu/data/ury.svg",
    callingCodes: ["+598"],
    currencyCode: "UYU",
  },
  {
    name: "Uzbekistan",
    alpha2Code: "UZ",
    emoji: "🇺🇿",
    flag: "https://restcountries.eu/data/uzb.svg",
    callingCodes: ["+998"],
    currencyCode: "UZS",
  },
  {
    name: "Vanuatu",
    alpha2Code: "VU",
    emoji: "🇻🇺",
    flag: "https://restcountries.eu/data/vut.svg",
    callingCodes: ["+678"],
    currencyCode: "VUV",
  },
  {
    name: "Venezuela",
    alpha2Code: "VE",
    emoji: "🇻🇪",
    flag: "https://restcountries.eu/data/ven.svg",
    callingCodes: ["+58"],
    currencyCode: "VEF",
  },
  {
    name: "Vietnam",
    alpha2Code: "VN",
    emoji: "🇻🇳",
    flag: "https://restcountries.eu/data/vnm.svg",
    callingCodes: ["+84"],
    currencyCode: "VND",
  },
  {
    name: "Wallis and Futuna",
    alpha2Code: "WF",
    emoji: "🇼🇫",
    flag: "https://restcountries.eu/data/wlf.svg",
    callingCodes: ["+681"],
    currencyCode: "XPF",
  },
  {
    name: "Western Sahara",
    alpha2Code: "EH",
    emoji: "🇪🇭",
    flag: "https://restcountries.eu/data/esh.svg",
    callingCodes: ["+212"],
    currencyCode: "MAD",
  },
  {
    name: "Yemen",
    alpha2Code: "YE",
    emoji: "🇾🇪",
    flag: "https://restcountries.eu/data/yem.svg",
    callingCodes: ["+967"],
    currencyCode: "YER",
  },
  {
    name: "Zambia",
    alpha2Code: "ZM",
    emoji: "🇿🇲",
    flag: "https://restcountries.eu/data/zmb.svg",
    callingCodes: ["+260"],
    currencyCode: "ZMW",
  },
  {
    name: "Zimbabwe",
    alpha2Code: "ZW",
    emoji: "🇿🇼",
    flag: "https://restcountries.eu/data/zwe.svg",
    callingCodes: ["+263"],
    currencyCode: "ZWL",
  },
];
